version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-promise
    versions:
    - 5.1.0
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 10.0.1
